# Generated by Django 4.0.2 on 2022-02-17 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='DID')),
                ('deviceSKU', models.CharField(max_length=30)),
                ('modelNum', models.CharField(max_length=30)),
                ('serialNum', models.CharField(max_length=30)),
                ('isAssigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('birthDate', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
    ]
