# Generated by Django 4.0.2 on 2022-02-21 23:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(max_length=30)),
                ('severity', models.CharField(choices=[('1', 'MILD'), ('2', 'SERIOUS'), ('3', 'URGENT')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='device',
            old_name='id',
            new_name='did',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='device',
            name='uid',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='myapi.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'ADMIN'), ('1', 'PCP'), ('2', 'Patient'), ('3', 'Other')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'SURGICAL'), ('2', 'PHYSICAL EXAM'), ('3', 'SCAN'), ('4', 'THERAPY'), ('5', 'REHABILITATION')], max_length=1)),
                ('performedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('medId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='DID')),
                ('isValid', models.BooleanField(default=False)),
                ('medhistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.medhistory')),
                ('prescribedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='medhistory',
            name='uid',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='myapi.user'),
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('did', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='myapi.device')),
                ('uid', models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('BMI', models.CharField(max_length=30)),
                ('bloodPressure', models.CharField(max_length=30)),
                ('bloodO2', models.CharField(max_length=30)),
                ('heartRate', models.CharField(max_length=30)),
                ('temperature', models.CharField(max_length=30)),
                ('measurements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.measurements')),
            ],
        ),
    ]
