# Generated by Django 4.0.2 on 2022-03-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_allergies_medhistory_rename_id_device_did_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
    ]
