# Generated by Django 4.0.2 on 2022-03-11 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_uid_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergies',
            name='medhistory',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='myapi.medhistory'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='medhistory',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='myapi.medhistory'),
        ),
        migrations.AddField(
            model_name='operation',
            name='medhistory',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='myapi.medhistory'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurements',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='myapi.measurements'),
        ),
        migrations.AlterField(
            model_name='medications',
            name='medhistory',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='myapi.medhistory'),
        ),
    ]
