# Generated by Django 4.0.2 on 2022-03-11 22:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_allergies_medhistory_measurements_medhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergies',
            name='allergy',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='medhistory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='myapi.medhistory'),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='severity',
            field=models.CharField(choices=[('1', 'MILD'), ('2', 'SERIOUS'), ('3', 'URGENT')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='myapi.user'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='BMI',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='bloodO2',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='bloodPressure',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='heartRate',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='height',
            field=models.CharField(default='0cm', max_length=30),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.CharField(default='0kg', max_length=30),
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='uid',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medHistory', to='myapi.user'),
        ),
        migrations.AlterField(
            model_name='medications',
            name='medId',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='medID'),
        ),
        migrations.AlterField(
            model_name='medications',
            name='medhistory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='myapi.medhistory'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='medhistory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='myapi.medhistory'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('1', 'SURGICAL'), ('2', 'PHYSICAL EXAM'), ('3', 'SCAN'), ('4', 'THERAPY'), ('5', 'REHABILITATION')], default='5', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='1 Main Street', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.CharField(default='01/01/01', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='Johnny', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='Appleseed', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
