# Generated by Django 4.0.2 on 2022-03-11 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_allergies_medhistory_alter_device_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='prescribedBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriber', to='myapi.user'),
        ),
    ]
